<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Country;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Country::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $countries = [
            array('name' => 'Afghanistan','iso2' => 'AF','iso3' => 'AFG','phone_code' => '93','currency_name' => 'Afghani','currency_code' => 'AFN','currency_symbol' => '؋'),
            array('name' => 'Albania','iso2' => 'AL','iso3' => 'ALB','phone_code' => '355','currency_name' => 'Lek','currency_code' => 'ALL','currency_symbol' => 'Lek'),
            array('name' => 'Algeria','iso2' => 'DZ','iso3' => 'DZA','phone_code' => '213','currency_name' => 'Dinar','currency_code' => 'DZD','currency_symbol' => ''),
            array('name' => 'American Samoa','iso2' => 'AS','iso3' => 'ASM','phone_code' => '1684','currency_name' => 'Dollar','currency_code' => 'USD','currency_symbol' => '$'),
            array('name' => 'Andorra','iso2' => 'AD','iso3' => 'AND','phone_code' => '376','currency_name' => 'Euro','currency_code' => 'EUR','currency_symbol' => '€'),
            array('name' => 'Angola','iso2' => 'AO','iso3' => 'AGO','phone_code' => '244','currency_name' => 'Kwanza','currency_code' => 'AOA','currency_symbol' => 'Kz'),
            array('name' => 'Anguilla','iso2' => 'AI','iso3' => 'AIA','phone_code' => '1264','currency_name' => 'Dollar','currency_code' => 'XCD','currency_symbol' => '$'),
            array('name' => 'Antarctica','iso2' => 'AQ','iso3' => 'ATA','phone_code' => '672','currency_name' => '','currency_code' => '','currency_symbol' => ''),
            array('name' => 'Antigua and Barbuda','iso2' => 'AG','iso3' => 'ATG','phone_code' => '1268','currency_name' => 'Dollar','currency_code' => 'XCD','currency_symbol' => '$'),
            array('name' => 'Argentina','iso2' => 'AR','iso3' => 'ARG','phone_code' => '54','currency_name' => 'Peso','currency_code' => 'ARS','currency_symbol' => '$'),
            array('name' => 'Armenia','iso2' => 'AM','iso3' => 'ARM','phone_code' => '374','currency_name' => 'Dram','currency_code' => 'AMD','currency_symbol' => ''),
            array('name' => 'Aruba','iso2' => 'AW','iso3' => 'ABW','phone_code' => '297','currency_name' => 'Guilder','currency_code' => 'AWG','currency_symbol' => 'ƒ'),
            array('name' => 'Australia','iso2' => 'AU','iso3' => 'AUS','phone_code' => '61','currency_name' => 'Dollar','currency_code' => 'AUD','currency_symbol' => '$'),
            array('name' => 'Austria','iso2' => 'AT','iso3' => 'AUT','phone_code' => '43','currency_name' => 'Euro','currency_code' => 'EUR','currency_symbol' => '€'),
            array('name' => 'Azerbaijan','iso2' => 'AZ','iso3' => 'AZE','phone_code' => '994','currency_name' => 'Manat','currency_code' => 'AZN','currency_symbol' => 'ман'),
            array('name' => 'Bahamas','iso2' => 'BS','iso3' => 'BHS','phone_code' => '1242','currency_name' => 'Dollar','currency_code' => 'BSD','currency_symbol' => '$'),
            array('name' => 'Bahrain','iso2' => 'BH','iso3' => 'BHR','phone_code' => '973','currency_name' => 'Dinar','currency_code' => 'BHD','currency_symbol' => ''),
            array('name' => 'Bangladesh','iso2' => 'BD','iso3' => 'BGD','phone_code' => '880','currency_name' => 'Taka','currency_code' => 'BDT','currency_symbol' => ''),
            array('name' => 'Barbados','iso2' => 'BB','iso3' => 'BRB','phone_code' => '1246','currency_name' => 'Dollar','currency_code' => 'BBD','currency_symbol' => '$'),
            array('name' => 'Belarus','iso2' => 'BY','iso3' => 'BLR','phone_code' => '375','currency_name' => 'Ruble','currency_code' => 'BYR','currency_symbol' => 'p.'),
            array('name' => 'Belgium','iso2' => 'BE','iso3' => 'BEL','phone_code' => '32','currency_name' => 'Euro','currency_code' => 'EUR','currency_symbol' => '€'),
            array('name' => 'Belize','iso2' => 'BZ','iso3' => 'BLZ','phone_code' => '501','currency_name' => 'Dollar','currency_code' => 'BZD','currency_symbol' => 'BZ$'),
            array('name' => 'Benin','iso2' => 'BJ','iso3' => 'BEN','phone_code' => '229','currency_name' => 'Franc','currency_code' => 'XOF','currency_symbol' => ''),
            array('name' => 'Bermuda','iso2' => 'BM','iso3' => 'BMU','phone_code' => '1441','currency_name' => 'Dollar','currency_code' => 'BMD','currency_symbol' => '$'),
            array('name' => 'Bhutan','iso2' => 'BT','iso3' => 'BTN','phone_code' => '975','currency_name' => 'Ngultrum','currency_code' => 'BTN','currency_symbol' => ''),
            array('name' => 'Bolivia','iso2' => 'BO','iso3' => 'BOL','phone_code' => '591','currency_name' => 'Boliviano','currency_code' => 'BOB','currency_symbol' => '$b'),
            array('name' => 'Bosnia and Herzegovina','iso2' => 'BA','iso3' => 'BIH','phone_code' => '387','currency_name' => 'Marka','currency_code' => 'BAM','currency_symbol' => 'KM'),
            array('name' => 'Botswana','iso2' => 'BW','iso3' => 'BWA','phone_code' => '267','currency_name' => 'Pula','currency_code' => 'BWP','currency_symbol' => 'P'),
            array('name' => 'Bouvet Island','iso2' => 'BV','iso3' => 'BVT','phone_code' => '','currency_name' => 'Krone','currency_code' => 'NOK','currency_symbol' => 'kr'),
            array('name' => 'Brazil','iso2' => 'BR','iso3' => 'BRA','phone_code' => '55','currency_name' => 'Real','currency_code' => 'BRL','currency_symbol' => 'R$'),
            array('name' => 'British Indian Ocean Territory','iso2' => 'IO','iso3' => 'IOT','phone_code' => '','currency_name' => 'Dollar','currency_code' => 'USD','currency_symbol' => '$'),
            array('name' => 'British Virgin Islands','iso2' => 'VG','iso3' => 'VGB','phone_code' => '1284','currency_name' => 'Dollar','currency_code' => 'USD','currency_symbol' => '$'),
            array('name' => 'Brunei','iso2' => 'BN','iso3' => 'BRN','phone_code' => '673','currency_name' => 'Dollar','currency_code' => 'BND','currency_symbol' => '$'),
            array('name' => 'Bulgaria','iso2' => 'BG','iso3' => 'BGR','phone_code' => '359','currency_name' => 'Lev','currency_code' => 'BGN','currency_symbol' => 'лв'),
            array('name' => 'Burkina Faso','iso2' => 'BF','iso3' => 'BFA','phone_code' => '226','currency_name' => 'Franc','currency_code' => 'XOF','currency_symbol' => ''),
            array('name' => 'Burundi','iso2' => 'BI','iso3' => 'BDI','phone_code' => '257','currency_name' => 'Franc','currency_code' => 'BIF','currency_symbol' => ''),
            array('name' => 'Cambodia','iso2' => 'KH','iso3' => 'KHM','phone_code' => '855','currency_name' => 'Riels','currency_code' => 'KHR','currency_symbol' => '៛'),
            array('name' => 'Cameroon','iso2' => 'CM','iso3' => 'CMR','phone_code' => '237','currency_name' => 'Franc','currency_code' => 'XAF','currency_symbol' => 'FCF'),
            array('name' => 'Canada','iso2' => 'CA','iso3' => 'CAN','phone_code' => '1','currency_name' => 'Dollar','currency_code' => 'CAD','currency_symbol' => '$'),
            array('name' => 'Cape Verde','iso2' => 'CV','iso3' => 'CPV','phone_code' => '238','currency_name' => 'Escudo','currency_code' => 'CVE','currency_symbol' => ''),
            array('name' => 'Cayman Islands','iso2' => 'KY','iso3' => 'CYM','phone_code' => '1345','currency_name' => 'Dollar','currency_code' => 'KYD','currency_symbol' => '$'),
            array('name' => 'Central African Republic','iso2' => 'CF','iso3' => 'CAF','phone_code' => '236','currency_name' => 'Franc','currency_code' => 'XAF','currency_symbol' => 'FCF'),
            array('name' => 'Chad','iso2' => 'TD','iso3' => 'TCD','phone_code' => '235','currency_name' => 'Franc','currency_code' => 'XAF','currency_symbol' => ''),
            array('name' => 'Chile','iso2' => 'CL','iso3' => 'CHL','phone_code' => '56','currency_name' => 'Peso','currency_code' => 'CLP','currency_symbol' => ''),
            array('name' => 'China','iso2' => 'CN','iso3' => 'CHN','phone_code' => '86','currency_name' => 'Yuan Renminbi','currency_code' => 'CNY','currency_symbol' => '¥'),
            array('name' => 'Christmas Island','iso2' => 'CX','iso3' => 'CXR','phone_code' => '61','currency_name' => 'Dollar','currency_code' => 'AUD','currency_symbol' => '$'),
            array('name' => 'Cocos Islands','iso2' => 'CC','iso3' => 'CCK','phone_code' => '61','currency_name' => 'Dollar','currency_code' => 'AUD','currency_symbol' => '$'),
            array('name' => 'Colombia','iso2' => 'CO','iso3' => 'COL','phone_code' => '57','currency_name' => 'Peso','currency_code' => 'COP','currency_symbol' => '$'),
            array('name' => 'Comoros','iso2' => 'KM','iso3' => 'COM','phone_code' => '269','currency_name' => 'Franc','currency_code' => 'KMF','currency_symbol' => ''),
            array('name' => 'Cook Islands','iso2' => 'CK','iso3' => 'COK','phone_code' => '682','currency_name' => 'Dollar','currency_code' => 'NZD','currency_symbol' => '$'),
            array('name' => 'Costa Rica','iso2' => 'CR','iso3' => 'CRI','phone_code' => '506','currency_name' => 'Colon','currency_code' => 'CRC','currency_symbol' => '₡'),
            array('name' => 'Croatia','iso2' => 'HR','iso3' => 'HRV','phone_code' => '385','currency_name' => 'Kuna','currency_code' => 'HRK','currency_symbol' => 'kn'),
            array('name' => 'Cuba','iso2' => 'CU','iso3' => 'CUB','phone_code' => '53','currency_name' => 'Peso','currency_code' => 'CUP','currency_symbol' => '₱'),
            array('name' => 'Cyprus','iso2' => 'CY','iso3' => 'CYP','phone_code' => '357','currency_name' => 'Pound','currency_code' => 'CYP','currency_symbol' => ''),
            array('name' => 'Czech Republic','iso2' => 'CZ','iso3' => 'CZE','phone_code' => '420','currency_name' => 'Koruna','currency_code' => 'CZK','currency_symbol' => 'Kč'),
            array('name' => 'Democratic Republic of the Congo','iso2' => 'CD','iso3' => 'COD','phone_code' => '243','currency_name' => 'Franc','currency_code' => 'CDF','currency_symbol' => ''),
            array('name' => 'Denmark','iso2' => 'DK','iso3' => 'DNK','phone_code' => '45','currency_name' => 'Krone','currency_code' => 'DKK','currency_symbol' => 'kr'),
            array('name' => 'Djibouti','iso2' => 'DJ','iso3' => 'DJI','phone_code' => '253','currency_name' => 'Franc','currency_code' => 'DJF','currency_symbol' => ''),
            array('name' => 'Dominica','iso2' => 'DM','iso3' => 'DMA','phone_code' => '1767','currency_name' => 'Dollar','currency_code' => 'XCD','currency_symbol' => '$'),
            array('name' => 'Dominican Republic','iso2' => 'DO','iso3' => 'DOM','phone_code' => '1809','currency_name' => 'Peso','currency_code' => 'DOP','currency_symbol' => 'RD$'),
            array('name' => 'East Timor','iso2' => 'TL','iso3' => 'TLS','phone_code' => '670','currency_name' => 'Dollar','currency_code' => 'USD','currency_symbol' => '$'),
            array('name' => 'Ecuador','iso2' => 'EC','iso3' => 'ECU','phone_code' => '593','currency_name' => 'Dollar','currency_code' => 'USD','currency_symbol' => '$'),
            array('name' => 'Egypt','iso2' => 'EG','iso3' => 'EGY','phone_code' => '20','currency_name' => 'Pound','currency_code' => 'EGP','currency_symbol' => '£'),
            array('name' => 'El Salvador','iso2' => 'SV','iso3' => 'SLV','phone_code' => '503','currency_name' => 'Colone','currency_code' => 'SVC','currency_symbol' => '$'),
            array('name' => 'Equatorial Guinea','iso2' => 'GQ','iso3' => 'GNQ','phone_code' => '240','currency_name' => 'Franc','currency_code' => 'XAF','currency_symbol' => 'FCF'),
            array('name' => 'Eritrea','iso2' => 'ER','iso3' => 'ERI','phone_code' => '291','currency_name' => 'Nakfa','currency_code' => 'ERN','currency_symbol' => 'Nfk'),
            array('name' => 'Estonia','iso2' => 'EE','iso3' => 'EST','phone_code' => '372','currency_name' => 'Kroon','currency_code' => 'EEK','currency_symbol' => 'kr'),
            array('name' => 'Ethiopia','iso2' => 'ET','iso3' => 'ETH','phone_code' => '251','currency_name' => 'Birr','currency_code' => 'ETB','currency_symbol' => ''),
            array('name' => 'Falkland Islands','iso2' => 'FK','iso3' => 'FLK','phone_code' => '500','currency_name' => 'Pound','currency_code' => 'FKP','currency_symbol' => '£'),
            array('name' => 'Faroe Islands','iso2' => 'FO','iso3' => 'FRO','phone_code' => '298','currency_name' => 'Krone','currency_code' => 'DKK','currency_symbol' => 'kr'),
            array('name' => 'Fiji','iso2' => 'FJ','iso3' => 'FJI','phone_code' => '679','currency_name' => 'Dollar','currency_code' => 'FJD','currency_symbol' => '$'),
            array('name' => 'Finland','iso2' => 'FI','iso3' => 'FIN','phone_code' => '358','currency_name' => 'Euro','currency_code' => 'EUR','currency_symbol' => '€'),
            array('name' => 'France','iso2' => 'FR','iso3' => 'FRA','phone_code' => '33','currency_name' => 'Euro','currency_code' => 'EUR','currency_symbol' => '€'),
            array('name' => 'French Guiana','iso2' => 'GF','iso3' => 'GUF','phone_code' => '','currency_name' => 'Euro','currency_code' => 'EUR','currency_symbol' => '€'),
            array('name' => 'French Polynesia','iso2' => 'PF','iso3' => 'PYF','phone_code' => '689','currency_name' => 'Franc','currency_code' => 'XPF','currency_symbol' => ''),
            array('name' => 'French Southern Territories','iso2' => 'TF','iso3' => 'ATF','phone_code' => '','currency_name' => 'Euro','currency_code' => 'EUR','currency_symbol' => '€'),
            array('name' => 'Gabon','iso2' => 'GA','iso3' => 'GAB','phone_code' => '241','currency_name' => 'Franc','currency_code' => 'XAF','currency_symbol' => 'FCF'),
            array('name' => 'Gambia','iso2' => 'GM','iso3' => 'GMB','phone_code' => '220','currency_name' => 'Dalasi','currency_code' => 'GMD','currency_symbol' => 'D'),
            array('name' => 'Georgia','iso2' => 'GE','iso3' => 'GEO','phone_code' => '995','currency_name' => 'Lari','currency_code' => 'GEL','currency_symbol' => ''),
            array('name' => 'Germany','iso2' => 'DE','iso3' => 'DEU','phone_code' => '49','currency_name' => 'Euro','currency_code' => 'EUR','currency_symbol' => '€'),
            array('name' => 'Ghana','iso2' => 'GH','iso3' => 'GHA','phone_code' => '233','currency_name' => 'Cedi','currency_code' => 'GHC','currency_symbol' => '¢'),
            array('name' => 'Gibraltar','iso2' => 'GI','iso3' => 'GIB','phone_code' => '350','currency_name' => 'Pound','currency_code' => 'GIP','currency_symbol' => '£'),
            array('name' => 'Greece','iso2' => 'GR','iso3' => 'GRC','phone_code' => '30','currency_name' => 'Euro','currency_code' => 'EUR','currency_symbol' => '€'),
            array('name' => 'Greenland','iso2' => 'GL','iso3' => 'GRL','phone_code' => '299','currency_name' => 'Krone','currency_code' => 'DKK','currency_symbol' => 'kr'),
            array('name' => 'Grenada','iso2' => 'GD','iso3' => 'GRD','phone_code' => '1473','currency_name' => 'Dollar','currency_code' => 'XCD','currency_symbol' => '$'),
            array('name' => 'Guadeloupe','iso2' => 'GP','iso3' => 'GLP','phone_code' => '','currency_name' => 'Euro','currency_code' => 'EUR','currency_symbol' => '€'),
            array('name' => 'Guam','iso2' => 'GU','iso3' => 'GUM','phone_code' => '1671','currency_name' => 'Dollar','currency_code' => 'USD','currency_symbol' => '$'),
            array('name' => 'Guatemala','iso2' => 'GT','iso3' => 'GTM','phone_code' => '502','currency_name' => 'Quetzal','currency_code' => 'GTQ','currency_symbol' => 'Q'),
            array('name' => 'Guinea','iso2' => 'GN','iso3' => 'GIN','phone_code' => '224','currency_name' => 'Franc','currency_code' => 'GNF','currency_symbol' => ''),
            array('name' => 'Guinea-Bissau','iso2' => 'GW','iso3' => 'GNB','phone_code' => '245','currency_name' => 'Franc','currency_code' => 'XOF','currency_symbol' => ''),
            array('name' => 'Guyana','iso2' => 'GY','iso3' => 'GUY','phone_code' => '592','currency_name' => 'Dollar','currency_code' => 'GYD','currency_symbol' => '$'),
            array('name' => 'Haiti','iso2' => 'HT','iso3' => 'HTI','phone_code' => '509','currency_name' => 'Gourde','currency_code' => 'HTG','currency_symbol' => 'G'),
            array('name' => 'Heard Island and McDonald Islands','iso2' => 'HM','iso3' => 'HMD','phone_code' => '','currency_name' => 'Dollar','currency_code' => 'AUD','currency_symbol' => '$'),
            array('name' => 'Honduras','iso2' => 'HN','iso3' => 'HND','phone_code' => '504','currency_name' => 'Lempira','currency_code' => 'HNL','currency_symbol' => 'L'),
            array('name' => 'Hong Kong','iso2' => 'HK','iso3' => 'HKG','phone_code' => '852','currency_name' => 'Dollar','currency_code' => 'HKD','currency_symbol' => '$'),
            array('name' => 'Hungary','iso2' => 'HU','iso3' => 'HUN','phone_code' => '36','currency_name' => 'Forint','currency_code' => 'HUF','currency_symbol' => 'Ft'),
            array('name' => 'Iceland','iso2' => 'IS','iso3' => 'ISL','phone_code' => '354','currency_name' => 'Krona','currency_code' => 'ISK','currency_symbol' => 'kr'),
            array('name' => 'India','iso2' => 'IN','iso3' => 'IND','phone_code' => '91','currency_name' => 'Rupee','currency_code' => 'INR','currency_symbol' => '₹'),
            array('name' => 'Indonesia','iso2' => 'ID','iso3' => 'IDN','phone_code' => '62','currency_name' => 'Rupiah','currency_code' => 'IDR','currency_symbol' => 'Rp'),
            array('name' => 'Iran','iso2' => 'IR','iso3' => 'IRN','phone_code' => '98','currency_name' => 'Rial','currency_code' => 'IRR','currency_symbol' => '﷼'),
            array('name' => 'Iraq','iso2' => 'IQ','iso3' => 'IRQ','phone_code' => '964','currency_name' => 'Dinar','currency_code' => 'IQD','currency_symbol' => ''),
            array('name' => 'Ireland','iso2' => 'IE','iso3' => 'IRL','phone_code' => '353','currency_name' => 'Euro','currency_code' => 'EUR','currency_symbol' => '€'),
            array('name' => 'Israel','iso2' => 'IL','iso3' => 'ISR','phone_code' => '972','currency_name' => 'Shekel','currency_code' => 'ILS','currency_symbol' => '₪'),
            array('name' => 'Italy','iso2' => 'IT','iso3' => 'ITA','phone_code' => '39','currency_name' => 'Euro','currency_code' => 'EUR','currency_symbol' => '€'),
            array('name' => 'Ivory Coast','iso2' => 'CI','iso3' => 'CIV','phone_code' => '225','currency_name' => 'Franc','currency_code' => 'XOF','currency_symbol' => ''),
            array('name' => 'Jamaica','iso2' => 'JM','iso3' => 'JAM','phone_code' => '1876','currency_name' => 'Dollar','currency_code' => 'JMD','currency_symbol' => '$'),
            array('name' => 'Japan','iso2' => 'JP','iso3' => 'JPN','phone_code' => '81','currency_name' => 'Yen','currency_code' => 'JPY','currency_symbol' => '¥'),
            array('name' => 'Jordan','iso2' => 'JO','iso3' => 'JOR','phone_code' => '962','currency_name' => 'Dinar','currency_code' => 'JOD','currency_symbol' => ''),
            array('name' => 'Kazakhstan','iso2' => 'KZ','iso3' => 'KAZ','phone_code' => '7','currency_name' => 'Tenge','currency_code' => 'KZT','currency_symbol' => 'лв'),
            array('name' => 'Kenya','iso2' => 'KE','iso3' => 'KEN','phone_code' => '254','currency_name' => 'Shilling','currency_code' => 'KES','currency_symbol' => ''),
            array('name' => 'Kiribati','iso2' => 'KI','iso3' => 'KIR','phone_code' => '686','currency_name' => 'Dollar','currency_code' => 'AUD','currency_symbol' => '$'),
            array('name' => 'Kuwait','iso2' => 'KW','iso3' => 'KWT','phone_code' => '965','currency_name' => 'Dinar','currency_code' => 'KWD','currency_symbol' => ''),
            array('name' => 'Kyrgyzstan','iso2' => 'KG','iso3' => 'KGZ','phone_code' => '996','currency_name' => 'Som','currency_code' => 'KGS','currency_symbol' => 'лв'),
            array('name' => 'Laos','iso2' => 'LA','iso3' => 'LAO','phone_code' => '856','currency_name' => 'Kip','currency_code' => 'LAK','currency_symbol' => '₭'),
            array('name' => 'Latvia','iso2' => 'LV','iso3' => 'LVA','phone_code' => '371','currency_name' => 'Lat','currency_code' => 'LVL','currency_symbol' => 'Ls'),
            array('name' => 'Lebanon','iso2' => 'LB','iso3' => 'LBN','phone_code' => '961','currency_name' => 'Pound','currency_code' => 'LBP','currency_symbol' => '£'),
            array('name' => 'Lesotho','iso2' => 'LS','iso3' => 'LSO','phone_code' => '266','currency_name' => 'Loti','currency_code' => 'LSL','currency_symbol' => 'L'),
            array('name' => 'Liberia','iso2' => 'LR','iso3' => 'LBR','phone_code' => '231','currency_name' => 'Dollar','currency_code' => 'LRD','currency_symbol' => '$'),
            array('name' => 'Libya','iso2' => 'LY','iso3' => 'LBY','phone_code' => '218','currency_name' => 'Dinar','currency_code' => 'LYD','currency_symbol' => ''),
            array('name' => 'Liechtenstein','iso2' => 'LI','iso3' => 'LIE','phone_code' => '423','currency_name' => 'Franc','currency_code' => 'CHF','currency_symbol' => 'CHF'),
            array('name' => 'Lithuania','iso2' => 'LT','iso3' => 'LTU','phone_code' => '370','currency_name' => 'Litas','currency_code' => 'LTL','currency_symbol' => 'Lt'),
            array('name' => 'Luxembourg','iso2' => 'LU','iso3' => 'LUX','phone_code' => '352','currency_name' => 'Euro','currency_code' => 'EUR','currency_symbol' => '€'),
            array('name' => 'Macao','iso2' => 'MO','iso3' => 'MAC','phone_code' => '853','currency_name' => 'Pataca','currency_code' => 'MOP','currency_symbol' => 'MOP'),
            array('name' => 'Macedonia','iso2' => 'MK','iso3' => 'MKD','phone_code' => '389','currency_name' => 'Denar','currency_code' => 'MKD','currency_symbol' => 'ден'),
            array('name' => 'Madagascar','iso2' => 'MG','iso3' => 'MDG','phone_code' => '261','currency_name' => 'Ariary','currency_code' => 'MGA','currency_symbol' => ''),
            array('name' => 'Malawi','iso2' => 'MW','iso3' => 'MWI','phone_code' => '265','currency_name' => 'Kwacha','currency_code' => 'MWK','currency_symbol' => 'MK'),
            array('name' => 'Malaysia','iso2' => 'MY','iso3' => 'MYS','phone_code' => '60','currency_name' => 'Ringgit','currency_code' => 'MYR','currency_symbol' => 'RM'),
            array('name' => 'Maldives','iso2' => 'MV','iso3' => 'MDV','phone_code' => '960','currency_name' => 'Rufiyaa','currency_code' => 'MVR','currency_symbol' => 'Rf'),
            array('name' => 'Mali','iso2' => 'ML','iso3' => 'MLI','phone_code' => '223','currency_name' => 'Franc','currency_code' => 'XOF','currency_symbol' => ''),
            array('name' => 'Malta','iso2' => 'MT','iso3' => 'MLT','phone_code' => '356','currency_name' => 'Lira','currency_code' => 'MTL','currency_symbol' => ''),
            array('name' => 'Marshall Islands','iso2' => 'MH','iso3' => 'MHL','phone_code' => '692','currency_name' => 'Dollar','currency_code' => 'USD','currency_symbol' => '$'),
            array('name' => 'Martinique','iso2' => 'MQ','iso3' => 'MTQ','phone_code' => '','currency_name' => 'Euro','currency_code' => 'EUR','currency_symbol' => '€'),
            array('name' => 'Mauritania','iso2' => 'MR','iso3' => 'MRT','phone_code' => '222','currency_name' => 'Ouguiya','currency_code' => 'MRO','currency_symbol' => 'UM'),
            array('name' => 'Mauritius','iso2' => 'MU','iso3' => 'MUS','phone_code' => '230','currency_name' => 'Rupee','currency_code' => 'MUR','currency_symbol' => '₨'),
            array('name' => 'Mayotte','iso2' => 'YT','iso3' => 'MYT','phone_code' => '262','currency_name' => 'Euro','currency_code' => 'EUR','currency_symbol' => '€'),
            array('name' => 'Mexico','iso2' => 'MX','iso3' => 'MEX','phone_code' => '52','currency_name' => 'Peso','currency_code' => 'MXN','currency_symbol' => '$'),
            array('name' => 'Micronesia','iso2' => 'FM','iso3' => 'FSM','phone_code' => '691','currency_name' => 'Dollar','currency_code' => 'USD','currency_symbol' => '$'),
            array('name' => 'Moldova','iso2' => 'MD','iso3' => 'MDA','phone_code' => '373','currency_name' => 'Leu','currency_code' => 'MDL','currency_symbol' => ''),
            array('name' => 'Monaco','iso2' => 'MC','iso3' => 'MCO','phone_code' => '377','currency_name' => 'Euro','currency_code' => 'EUR','currency_symbol' => '€'),
            array('name' => 'Mongolia','iso2' => 'MN','iso3' => 'MNG','phone_code' => '976','currency_name' => 'Tugrik','currency_code' => 'MNT','currency_symbol' => '₮'),
            array('name' => 'Montserrat','iso2' => 'MS','iso3' => 'MSR','phone_code' => '1664','currency_name' => 'Dollar','currency_code' => 'XCD','currency_symbol' => '$'),
            array('name' => 'Morocco','iso2' => 'MA','iso3' => 'MAR','phone_code' => '212','currency_name' => 'Dirham','currency_code' => 'MAD','currency_symbol' => ''),
            array('name' => 'Mozambique','iso2' => 'MZ','iso3' => 'MOZ','phone_code' => '258','currency_name' => 'Meticail','currency_code' => 'MZN','currency_symbol' => 'MT'),
            array('name' => 'Myanmar','iso2' => 'MM','iso3' => 'MMR','phone_code' => '95','currency_name' => 'Kyat','currency_code' => 'MMK','currency_symbol' => 'K'),
            array('name' => 'Namibia','iso2' => 'NA','iso3' => 'NAM','phone_code' => '264','currency_name' => 'Dollar','currency_code' => 'NAD','currency_symbol' => '$'),
            array('name' => 'Nauru','iso2' => 'NR','iso3' => 'NRU','phone_code' => '674','currency_name' => 'Dollar','currency_code' => 'AUD','currency_symbol' => '$'),
            array('name' => 'Nepal','iso2' => 'NP','iso3' => 'NPL','phone_code' => '977','currency_name' => 'Rupee','currency_code' => 'NPR','currency_symbol' => '₨'),
            array('name' => 'Netherlands','iso2' => 'NL','iso3' => 'NLD','phone_code' => '31','currency_name' => 'Euro','currency_code' => 'EUR','currency_symbol' => '€'),
            array('name' => 'Netherlands Antilles','iso2' => 'AN','iso3' => 'ANT','phone_code' => '599','currency_name' => 'Guilder','currency_code' => 'ANG','currency_symbol' => 'ƒ'),
            array('name' => 'New Caledonia','iso2' => 'NC','iso3' => 'NCL','phone_code' => '687','currency_name' => 'Franc','currency_code' => 'XPF','currency_symbol' => ''),
            array('name' => 'New Zealand','iso2' => 'NZ','iso3' => 'NZL','phone_code' => '64','currency_name' => 'Dollar','currency_code' => 'NZD','currency_symbol' => '$'),
            array('name' => 'Nicaragua','iso2' => 'NI','iso3' => 'NIC','phone_code' => '505','currency_name' => 'Cordoba','currency_code' => 'NIO','currency_symbol' => 'C$'),
            array('name' => 'Niger','iso2' => 'NE','iso3' => 'NER','phone_code' => '227','currency_name' => 'Franc','currency_code' => 'XOF','currency_symbol' => ''),
            array('name' => 'Nigeria','iso2' => 'NG','iso3' => 'NGA','phone_code' => '234','currency_name' => 'Naira','currency_code' => 'NGN','currency_symbol' => '₦'),
            array('name' => 'Niue','iso2' => 'NU','iso3' => 'NIU','phone_code' => '683','currency_name' => 'Dollar','currency_code' => 'NZD','currency_symbol' => '$'),
            array('name' => 'Norfolk Island','iso2' => 'NF','iso3' => 'NFK','phone_code' => '','currency_name' => 'Dollar','currency_code' => 'AUD','currency_symbol' => '$'),
            array('name' => 'North Korea','iso2' => 'KP','iso3' => 'PRK','phone_code' => '850','currency_name' => 'Won','currency_code' => 'KPW','currency_symbol' => '₩'),
            array('name' => 'Northern Mariana Islands','iso2' => 'MP','iso3' => 'MNP','phone_code' => '1670','currency_name' => 'Dollar','currency_code' => 'USD','currency_symbol' => '$'),
            array('name' => 'Norway','iso2' => 'NO','iso3' => 'NOR','phone_code' => '47','currency_name' => 'Krone','currency_code' => 'NOK','currency_symbol' => 'kr'),
            array('name' => 'Oman','iso2' => 'OM','iso3' => 'OMN','phone_code' => '968','currency_name' => 'Rial','currency_code' => 'OMR','currency_symbol' => '﷼'),
            array('name' => 'Pakistan','iso2' => 'PK','iso3' => 'PAK','phone_code' => '92','currency_name' => 'Rupee','currency_code' => 'PKR','currency_symbol' => '₨'),
            array('name' => 'Palau','iso2' => 'PW','iso3' => 'PLW','phone_code' => '680','currency_name' => 'Dollar','currency_code' => 'USD','currency_symbol' => '$'),
            array('name' => 'Palestinian Territory','iso2' => 'PS','iso3' => 'PSE','phone_code' => '','currency_name' => 'Shekel','currency_code' => 'ILS','currency_symbol' => '₪'),
            array('name' => 'Panama','iso2' => 'PA','iso3' => 'PAN','phone_code' => '507','currency_name' => 'Balboa','currency_code' => 'PAB','currency_symbol' => 'B/.'),
            array('name' => 'Papua New Guinea','iso2' => 'PG','iso3' => 'PNG','phone_code' => '675','currency_name' => 'Kina','currency_code' => 'PGK','currency_symbol' => ''),
            array('name' => 'Paraguay','iso2' => 'PY','iso3' => 'PRY','phone_code' => '595','currency_name' => 'Guarani','currency_code' => 'PYG','currency_symbol' => 'Gs'),
            array('name' => 'Peru','iso2' => 'PE','iso3' => 'PER','phone_code' => '51','currency_name' => 'Sol','currency_code' => 'PEN','currency_symbol' => 'S/.'),
            array('name' => 'Philippines','iso2' => 'PH','iso3' => 'PHL','phone_code' => '63','currency_name' => 'Peso','currency_code' => 'PHP','currency_symbol' => 'Php'),
            array('name' => 'Pitcairn','iso2' => 'PN','iso3' => 'PCN','phone_code' => '870','currency_name' => 'Dollar','currency_code' => 'NZD','currency_symbol' => '$'),
            array('name' => 'Poland','iso2' => 'PL','iso3' => 'POL','phone_code' => '48','currency_name' => 'Zloty','currency_code' => 'PLN','currency_symbol' => 'zł'),
            array('name' => 'Portugal','iso2' => 'PT','iso3' => 'PRT','phone_code' => '351','currency_name' => 'Euro','currency_code' => 'EUR','currency_symbol' => '€'),
            array('name' => 'Puerto Rico','iso2' => 'PR','iso3' => 'PRI','phone_code' => '1','currency_name' => 'Dollar','currency_code' => 'USD','currency_symbol' => '$'),
            array('name' => 'Qatar','iso2' => 'QA','iso3' => 'QAT','phone_code' => '974','currency_name' => 'Rial','currency_code' => 'QAR','currency_symbol' => '﷼'),
            array('name' => 'Republic of the Congo','iso2' => 'CG','iso3' => 'COG','phone_code' => '242','currency_name' => 'Franc','currency_code' => 'XAF','currency_symbol' => 'FCF'),
            array('name' => 'Reunion','iso2' => 'RE','iso3' => 'REU','phone_code' => '','currency_name' => 'Euro','currency_code' => 'EUR','currency_symbol' => '€'),
            array('name' => 'Romania','iso2' => 'RO','iso3' => 'ROU','phone_code' => '40','currency_name' => 'Leu','currency_code' => 'RON','currency_symbol' => 'lei'),
            array('name' => 'Russia','iso2' => 'RU','iso3' => 'RUS','phone_code' => '7','currency_name' => 'Ruble','currency_code' => 'RUB','currency_symbol' => 'руб'),
            array('name' => 'Rwanda','iso2' => 'RW','iso3' => 'RWA','phone_code' => '250','currency_name' => 'Franc','currency_code' => 'RWF','currency_symbol' => ''),
            array('name' => 'Saint Helena','iso2' => 'SH','iso3' => 'SHN','phone_code' => '290','currency_name' => 'Pound','currency_code' => 'SHP','currency_symbol' => '£'),
            array('name' => 'Saint Kitts and Nevis','iso2' => 'KN','iso3' => 'KNA','phone_code' => '1869','currency_name' => 'Dollar','currency_code' => 'XCD','currency_symbol' => '$'),
            array('name' => 'Saint Lucia','iso2' => 'LC','iso3' => 'LCA','phone_code' => '1758','currency_name' => 'Dollar','currency_code' => 'XCD','currency_symbol' => '$'),
            array('name' => 'Saint Pierre and Miquelon','iso2' => 'PM','iso3' => 'SPM','phone_code' => '508','currency_name' => 'Euro','currency_code' => 'EUR','currency_symbol' => '€'),
            array('name' => 'Saint Vincent and the Grenadines','iso2' => 'VC','iso3' => 'VCT','phone_code' => '1784','currency_name' => 'Dollar','currency_code' => 'XCD','currency_symbol' => '$'),
            array('name' => 'Samoa','iso2' => 'WS','iso3' => 'WSM','phone_code' => '685','currency_name' => 'Tala','currency_code' => 'WST','currency_symbol' => 'WS$'),
            array('name' => 'San Marino','iso2' => 'SM','iso3' => 'SMR','phone_code' => '378','currency_name' => 'Euro','currency_code' => 'EUR','currency_symbol' => '€'),
            array('name' => 'Sao Tome and Principe','iso2' => 'ST','iso3' => 'STP','phone_code' => '239','currency_name' => 'Dobra','currency_code' => 'STD','currency_symbol' => 'Db'),
            array('name' => 'Saudi Arabia','iso2' => 'SA','iso3' => 'SAU','phone_code' => '966','currency_name' => 'Rial','currency_code' => 'SAR','currency_symbol' => '﷼'),
            array('name' => 'Senegal','iso2' => 'SN','iso3' => 'SEN','phone_code' => '221','currency_name' => 'Franc','currency_code' => 'XOF','currency_symbol' => ''),
            array('name' => 'Serbia and Montenegro','iso2' => 'CS','iso3' => 'SCG','phone_code' => '','currency_name' => 'Dinar','currency_code' => 'RSD','currency_symbol' => 'Дин'),
            array('name' => 'Seychelles','iso2' => 'SC','iso3' => 'SYC','phone_code' => '248','currency_name' => 'Rupee','currency_code' => 'SCR','currency_symbol' => '₨'),
            array('name' => 'Sierra Leone','iso2' => 'SL','iso3' => 'SLE','phone_code' => '232','currency_name' => 'Leone','currency_code' => 'SLL','currency_symbol' => 'Le'),
            array('name' => 'Singapore','iso2' => 'SG','iso3' => 'SGP','phone_code' => '65','currency_name' => 'Dollar','currency_code' => 'SGD','currency_symbol' => '$'),
            array('name' => 'Slovakia','iso2' => 'SK','iso3' => 'SVK','phone_code' => '421','currency_name' => 'Koruna','currency_code' => 'SKK','currency_symbol' => 'Sk'),
            array('name' => 'Slovenia','iso2' => 'SI','iso3' => 'SVN','phone_code' => '386','currency_name' => 'Euro','currency_code' => 'EUR','currency_symbol' => '€'),
            array('name' => 'Solomon Islands','iso2' => 'SB','iso3' => 'SLB','phone_code' => '677','currency_name' => 'Dollar','currency_code' => 'SBD','currency_symbol' => '$'),
            array('name' => 'Somalia','iso2' => 'SO','iso3' => 'SOM','phone_code' => '252','currency_name' => 'Shilling','currency_code' => 'SOS','currency_symbol' => 'S'),
            array('name' => 'South Africa','iso2' => 'ZA','iso3' => 'ZAF','phone_code' => '27','currency_name' => 'Rand','currency_code' => 'ZAR','currency_symbol' => 'R'),
            array('name' => 'South Georgia and the South Sandwich Islands','iso2' => 'GS','iso3' => 'SGS','phone_code' => '','currency_name' => 'Pound','currency_code' => 'GBP','currency_symbol' => '£'),
            array('name' => 'South Korea','iso2' => 'KR','iso3' => 'KOR','phone_code' => '82','currency_name' => 'Won','currency_code' => 'KRW','currency_symbol' => '₩'),
            array('name' => 'Spain','iso2' => 'ES','iso3' => 'ESP','phone_code' => '34','currency_name' => 'Euro','currency_code' => 'EUR','currency_symbol' => '€'),
            array('name' => 'Sri Lanka','iso2' => 'LK','iso3' => 'LKA','phone_code' => '94','currency_name' => 'Rupee','currency_code' => 'LKR','currency_symbol' => '₨'),
            array('name' => 'Sudan','iso2' => 'SD','iso3' => 'SDN','phone_code' => '249','currency_name' => 'Dinar','currency_code' => 'SDD','currency_symbol' => ''),
            array('name' => 'Suriname','iso2' => 'SR','iso3' => 'SUR','phone_code' => '597','currency_name' => 'Dollar','currency_code' => 'SRD','currency_symbol' => '$'),
            array('name' => 'Svalbard and Jan Mayen','iso2' => 'SJ','iso3' => 'SJM','phone_code' => '','currency_name' => 'Krone','currency_code' => 'NOK','currency_symbol' => 'kr'),
            array('name' => 'Swaziland','iso2' => 'SZ','iso3' => 'SWZ','phone_code' => '268','currency_name' => 'Lilangeni','currency_code' => 'SZL','currency_symbol' => ''),
            array('name' => 'Sweden','iso2' => 'SE','iso3' => 'SWE','phone_code' => '46','currency_name' => 'Krona','currency_code' => 'SEK','currency_symbol' => 'kr'),
            array('name' => 'Switzerland','iso2' => 'CH','iso3' => 'CHE','phone_code' => '41','currency_name' => 'Franc','currency_code' => 'CHF','currency_symbol' => 'CHF'),
            array('name' => 'Syria','iso2' => 'SY','iso3' => 'SYR','phone_code' => '963','currency_name' => 'Pound','currency_code' => 'SYP','currency_symbol' => '£'),
            array('name' => 'Taiwan','iso2' => 'TW','iso3' => 'TWN','phone_code' => '886','currency_name' => 'Dollar','currency_code' => 'TWD','currency_symbol' => 'NT$'),
            array('name' => 'Tajikistan','iso2' => 'TJ','iso3' => 'TJK','phone_code' => '992','currency_name' => 'Somoni','currency_code' => 'TJS','currency_symbol' => ''),
            array('name' => 'Tanzania','iso2' => 'TZ','iso3' => 'TZA','phone_code' => '255','currency_name' => 'Shilling','currency_code' => 'TZS','currency_symbol' => ''),
            array('name' => 'Thailand','iso2' => 'TH','iso3' => 'THA','phone_code' => '66','currency_name' => 'Baht','currency_code' => 'THB','currency_symbol' => '฿'),
            array('name' => 'Togo','iso2' => 'TG','iso3' => 'TGO','phone_code' => '228','currency_name' => 'Franc','currency_code' => 'XOF','currency_symbol' => ''),
            array('name' => 'Tokelau','iso2' => 'TK','iso3' => 'TKL','phone_code' => '690','currency_name' => 'Dollar','currency_code' => 'NZD','currency_symbol' => '$'),
            array('name' => 'Tonga','iso2' => 'TO','iso3' => 'TON','phone_code' => '676','currency_name' => 'Paanga','currency_code' => 'TOP','currency_symbol' => 'T$'),
            array('name' => 'Trinidad and Tobago','iso2' => 'TT','iso3' => 'TTO','phone_code' => '1868','currency_name' => 'Dollar','currency_code' => 'TTD','currency_symbol' => 'TT$'),
            array('name' => 'Tunisia','iso2' => 'TN','iso3' => 'TUN','phone_code' => '216','currency_name' => 'Dinar','currency_code' => 'TND','currency_symbol' => ''),
            array('name' => 'Turkey','iso2' => 'TR','iso3' => 'TUR','phone_code' => '90','currency_name' => 'Lira','currency_code' => 'TRY','currency_symbol' => 'YTL'),
            array('name' => 'Turkmenistan','iso2' => 'TM','iso3' => 'TKM','phone_code' => '993','currency_name' => 'Manat','currency_code' => 'TMM','currency_symbol' => 'm'),
            array('name' => 'Turks and Caicos Islands','iso2' => 'TC','iso3' => 'TCA','phone_code' => '1649','currency_name' => 'Dollar','currency_code' => 'USD','currency_symbol' => '$'),
            array('name' => 'Tuvalu','iso2' => 'TV','iso3' => 'TUV','phone_code' => '688','currency_name' => 'Dollar','currency_code' => 'AUD','currency_symbol' => '$'),
            array('name' => 'U.S. Virgin Islands','iso2' => 'VI','iso3' => 'VIR','phone_code' => '1340','currency_name' => 'Dollar','currency_code' => 'USD','currency_symbol' => '$'),
            array('name' => 'Uganda','iso2' => 'UG','iso3' => 'UGA','phone_code' => '256','currency_name' => 'Shilling','currency_code' => 'UGX','currency_symbol' => ''),
            array('name' => 'Ukraine','iso2' => 'UA','iso3' => 'UKR','phone_code' => '380','currency_name' => 'Hryvnia','currency_code' => 'UAH','currency_symbol' => '₴'),
            array('name' => 'United Arab Emirates','iso2' => 'AE','iso3' => 'ARE','phone_code' => '971','currency_name' => 'Dirham','currency_code' => 'AED','currency_symbol' => ''),
            array('name' => 'United Kingdom','iso2' => 'GB','iso3' => 'GBR','phone_code' => '44','currency_name' => 'Pound','currency_code' => 'GBP','currency_symbol' => '£'),
            array('name' => 'United States','iso2' => 'US','iso3' => 'USA','phone_code' => '1','currency_name' => 'Dollar','currency_code' => 'USD','currency_symbol' => '$'),
            array('name' => 'United States Minor Outlying Islands','iso2' => 'UM','iso3' => 'UMI','phone_code' => '','currency_name' => 'Dollar','currency_code' => 'USD','currency_symbol' => '$'),
            array('name' => 'Uruguay','iso2' => 'UY','iso3' => 'URY','phone_code' => '598','currency_name' => 'Peso','currency_code' => 'UYU','currency_symbol' => '$U'),
            array('name' => 'Uzbekistan','iso2' => 'UZ','iso3' => 'UZB','phone_code' => '998','currency_name' => 'Som','currency_code' => 'UZS','currency_symbol' => 'лв'),
            array('name' => 'Vanuatu','iso2' => 'VU','iso3' => 'VUT','phone_code' => '678','currency_name' => 'Vatu','currency_code' => 'VUV','currency_symbol' => 'Vt'),
            array('name' => 'Vatican','iso2' => 'VA','iso3' => 'VAT','phone_code' => '39','currency_name' => 'Euro','currency_code' => 'EUR','currency_symbol' => '€'),
            array('name' => 'Venezuela','iso2' => 'VE','iso3' => 'VEN','phone_code' => '58','currency_name' => 'Bolivar','currency_code' => 'VEF','currency_symbol' => 'Bs'),
            array('name' => 'Vietnam','iso2' => 'VN','iso3' => 'VNM','phone_code' => '84','currency_name' => 'Dong','currency_code' => 'VND','currency_symbol' => '₫'),
            array('name' => 'Wallis and Futuna','iso2' => 'WF','iso3' => 'WLF','phone_code' => '681','currency_name' => 'Franc','currency_code' => 'XPF','currency_symbol' => ''),
            array('name' => 'Western Sahara','iso2' => 'EH','iso3' => 'ESH','phone_code' => '','currency_name' => 'Dirham','currency_code' => 'MAD','currency_symbol' => ''),
            array('name' => 'Yemen','iso2' => 'YE','iso3' => 'YEM','phone_code' => '967','currency_name' => 'Rial','currency_code' => 'YER','currency_symbol' => '﷼'),
            array('name' => 'Zambia','iso2' => 'ZM','iso3' => 'ZMB','phone_code' => '260','currency_name' => 'Kwacha','currency_code' => 'ZMK','currency_symbol' => 'ZK'),
            array('name' => 'Zimbabwe','iso2' => 'ZW','iso3' => 'ZWE','phone_code' => '263','currency_name' => 'Dollar','currency_code' => 'ZWL','currency_symbol' => 'Z$')
        ];

        $currencySymbols = [
            'DZD' => 'د.ج', 'AOA' => 'Kz', 'AMD' => '֏', 'BHD' => 'BD', 'BDT' => '৳', 'BIF' => 'FBu',
            'XOF' => 'CFA', 'XAF' => 'CFA', 'CVE' => 'Esc', 'KMF' => 'CF', 'CDF' => 'FC', 'DJF' => 'Fdj',
            'EGP' => 'E£', 'ETB' => 'Br', 'XPF' => '₣', 'GEL' => '₾', 'GNF' => 'FG', 'IQD' => 'ع.د',
            'JOD' => 'JD', 'KES' => 'KSh', 'KWD' => 'KD', 'LBP' => 'L£', 'LYD' => 'LD', 'MGA' => 'Ar',
            'MAD' => 'DH', 'MMK' => 'K', 'NPR' => '₨', 'OMR' => '﷼', 'QAR' => 'QR', 'RWF' => 'FRw',
            'SAR' => 'SR', 'SLL' => 'Le', 'SOS' => 'Sh.So.', 'SDD' => 'LSd', 'SYP' => '£S',
            'TZS' => 'TSh', 'TND' => 'DT', 'UGX' => 'USh', 'AED' => 'DH'
        ];

        foreach($countries as &$country){
            if (empty($country['currency_symbol']) && isset($currencySymbols[$country['currency_code']])) {
                $country['currency_symbol'] = $currencySymbols[$country['currency_code']];
            }
        }

        foreach($countries as $country){
            $country['phone_code'] = str_replace(' ', '', $country['phone_code']);
            if($country['phone_code'] == ''){
                $country['phone_code'] = null;
            }
            Country::updateOrCreate(['name' => $country['name']], [
                'iso2' => $country['iso2'],
                'iso3' => $country['iso3'],
                'phone_code' => $country['phone_code'],
                'currency_name' => $country['currency_name'],
                'currency_code' => $country['currency_code'],
                'currency_symbol' => $country['currency_symbol'],
                'status' => 1,
            ]);
        }
    }
}
